### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'info2'

### ISSUE THREAD

**Issue by dpuza-formativ** [hartwork/svneverever#11]
```
Traceback (most recent call last):
  File "C:\Users\ME\AppData\Roaming\Python\Python38\site-packages\svnevere
ver\__main__.py", line 312, in main
    latest_revision = client.info2(
AttributeError: 'Client' object has no attribute 'info2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_mai
n
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ME\AppData\Roaming\Python\Python38\Scripts\svneverever.ex
e\__main__.py", line 7, in <module>
  File "C:\Users\ME\AppData\Roaming\Python\Python38\site-packages\svnevere
ver\__main__.py", line 314, in main
    except (pysvn.ClientError) as e:
AttributeError: module 'pysvn' has no attribute 'ClientError'
```

**Comment by hartwork** [comment]
@dpuza-formativ I have never used svneverever on Windows. I see you are using python 3.8. Which version of pysvn are you using? Which version of svneverever are you using?

**Comment by hartwork** [comment]
PS: @dpuza-formativ my guess is that you have the wrong pysvn. You need the one from https://pysvn.sourceforge.io/downloads.html (rather than https://pypi.org/project/pysvn/ which is https://github.com/leafvmaple/pysvn).

**Comment by hartwork** [comment]
I have added detection for the wrong pysvn now in release 1.6.0 and pushed that to PyPI to better communicate the situation to the user. I'm closing the issue as fixed. Please re-open this ticket as needed.

**Comment by dpuza-formativ** [comment]
@hartwork Thank you for responding.  I upgraded to svneverever-1.6.0 and have now installed pysvn 1.14.1 Win64 for python 3.8 from https://pysvn.sourceforge.io.
I now get the following error.  Do you know if there's something more I need to set up?  Or any idea what the problem might be?
`ERROR: callback_ssl_server_trust_prompt required`

**Comment by dpuza-formativ** [comment]
@hartwork Nevermind -- I found this and was able to proceed by doing an svn checkout and accepting the certificate as recommended there.  Now svneverever is processing my repository.  Thank you for your assistance!

https://answers.ros.org/question/28170/how-to-check-out-from-an-svn-that-requires-callback_ssl_server_trust_prompt

**Comment by hartwork** [comment]
@dpuza-formativ thanks for the update :+1:
